#no mixup final case
#CUDA_VISIBLE_DEVICES=3 python3 exp.py --grad_addback_weight 0 --cross_loss l1 --vul_metric loss --cross_loss_diff_lambda 12 --user_number 4  --target_data_size 1500 --num_step 15 --shadow_model_number 1 --std_loss_lambda 0 --fpr_threshold 0.001 --mixup 0 --repartition 1 --mmd_loss_lambda 0  --target_epochs 150  --dataset cifar100 --model_name alexnet --target_learning_rate 0.02 --target_l2_ratio 1e-5  --schedule 100 125 --local_epochs 1 --target_batch_size 100  ### 100 epochs
#CUDA_VISIBLE_DEVICES=0 python3 exp.py --grad_addback_weight 0  --cross_loss l1 --vul_metric loss --cross_loss_diff_lambda 5  --user_number 6  --target_data_size 3300 --num_step 33 --shadow_model_number 1  --std_loss_lambda 0 --fpr_threshold 0.001  --mixup 0 --repartition 1 --mmd_loss_lambda 0  --target_epochs 120  --dataset cifar10 --model_name alexnet --target_learning_rate 0.1 --target_l2_ratio 1e-5  --schedule 80 100   --local_epochs 1 --target_batch_size 100  ### 100 epochs
## block for alexnet
#12
#CUDA_VISIBLE_DEVICES=2 python3 exp.py --test_result 0 --label_only_attack 1 --grad_addback_weight 0 --cross_loss l1 --vul_metric loss --cross_loss_diff_lambda 12 --user_number 4 --target_data_size 5000 --num_step 50 --shadow_model_number 1 --std_loss_lambda 0 --fpr_threshold 0.001 --mixup 1 --repartition 1 --mmd_loss_lambda 0  --target_epochs 120  --dataset cifar100 --model_name alexnet --target_learning_rate 0.05 --target_l2_ratio 1e-5  --schedule 100  --local_epochs 1 --target_batch_size 100  ### 100 epochs
#3.5
#CUDA_VISIBLE_DEVICES=3 python3 exp.py -g-test_result 0  --label_only_attack 1  --grad_addback_weight 0  --cross_loss_diff_lambda 3.5 --user_number 2 --target_data_size 10000 --num_step 100 --cross_loss l1 --vul_metric loss --shadow_model_number 1 --std_loss_lambda 0 --fpr_threshold 0.001  --mixup 1 --repartition 1 --mmd_loss_lambda 0  --target_epochs 120  --dataset cifar10 --model_name alexnet --target_learning_rate 0.05 --target_l2_ratio 1e-5  --schedule 100   --local_epochs 1 --target_batch_size 100  ### 100 epochs
# alexnet basecase
#CUDA_VISIBLE_DEVICES=0 python3 exp.py  --label_only_attack 1 --test_result 0 --cross_loss_diff_lambda 0 --user_number 1  --target_data_size 20000 --num_step 200 --shadow_model_number 1  --std_loss_lambda 0 --fpr_threshold 0.001 --grad_addback_weight 0 --vul_metric loss  --mixup 0 --repartition 0 --mmd_loss_lambda 0  --target_epochs 120  --dataset cifar100 --model_name alexnet --target_learning_rate 0.01 --target_l2_ratio 1e-5  --schedule 100 --local_epochs 1 --target_batch_size 100  ### 100 epochs
#CUDA_VISIBLE_DEVICES=1 python3 exp.py --label_only_attack 1 --test_result 0  --cross_loss_diff_lambda 0 --user_number 1  --target_data_size 20000 --num_step 200 --shadow_model_number 1 --std_loss_lambda 0 --fpr_threshold 0.001 --grad_addback_weight 0 --vul_metric loss  --mixup 0 --repartition 0 --mmd_loss_lambda 0  --target_epochs 120 --dataset cifar10 --model_name alexnet --target_learning_rate 0.01 --target_l2_ratio 1e-5  --schedule 100   --local_epochs 1 --target_batch_size 100  ### 100 epochs
# alexnet basecase outlier exp
#CUDA_VISIBLE_DEVICES=0 python3 exp.py --ban_list 1  --label_only_attack 0 --test_result 0 --cross_loss_diff_lambda 0 --user_number 1  --target_data_size 19500 --num_step 195 --shadow_model_number 60  --std_loss_lambda 0 --fpr_threshold 0.001 --grad_addback_weight 0 --vul_metric loss  --mixup 0 --repartition 0 --mmd_loss_lambda 0  --target_epochs 120  --dataset cifar100 --model_name alexnet --target_learning_rate 0.01 --target_l2_ratio 1e-5  --schedule 100 --local_epochs 1 --target_batch_size 100  ### 100 epochs
#CUDA_VISIBLE_DEVICES=1 python3 exp.py --ban_list 1 --label_only_attack 0 --test_result 0  --cross_loss_diff_lambda 0 --user_number 1  --target_data_size 19500 --num_step 195 --shadow_model_number 60 --std_loss_lambda 0 --fpr_threshold 0.001 --grad_addback_weight 0 --vul_metric loss  --mixup 0 --repartition 0 --mmd_loss_lambda 0  --target_epochs 120 --dataset cifar10 --model_name alexnet --target_learning_rate 0.01 --target_l2_ratio 1e-5  --schedule 100   --local_epochs 1 --target_batch_size 100  ### 100 epochs
# mixup MMD
#CUDA_VISIBLE_DEVICES=0 python3 exp.py --test_result 0 --label_only_attack 1 --cross_loss_diff_lambda 0 --user_number 1  --target_data_size 20000 --num_step 200 --shadow_model_number 1  --std_loss_lambda 0 --fpr_threshold 0.001 --grad_addback_weight 0 --vul_metric loss  --mixup 1 --repartition 0 --mmd_loss_lambda 16  --target_epochs 120  --dataset cifar100 --model_name alexnet --target_learning_rate 0.01 --target_l2_ratio 1e-5  --schedule 100  --local_epochs 1 --target_batch_size 100  ### 100 epochs
#CUDA_VISIBLE_DEVICES=1 python3 exp.py --test_result 0 --label_only_attack 1 --cross_loss_diff_lambda 0 --user_number 1  --target_data_size 20000 --num_step 200 --shadow_model_number 10 --std_loss_lambda 0 --fpr_threshold 0.001 --grad_addback_weight 0 --vul_metric loss  --mixup 1 --repartition 0 --mmd_loss_lambda 0.25 --target_epochs 120 --dataset cifar10 --model_name alexnet --target_learning_rate 0.01 --target_l2_ratio 1e-5  --schedule 100  --local_epochs 1 --target_batch_size 100  ### 100 epochs
# alexnet basecase num user exp
#CUDA_VISIBLE_DEVICES=3 python3 exp.py --target_learning_rate 0.05 --simplex 0 --user_number 12 --target_data_size 1600  --num_step 16 --cross_loss_diff_lambda 0 --shadow_model_number 10 --std_loss_lambda 0 --fpr_threshold 0.001 --grad_addback_weight 0 --vul_metric loss  --mixup 0 --repartition 1 --mmd_loss_lambda 0  --target_epochs 120  --dataset cifar100 --model_name alexnet --target_l2_ratio 1e-5  --schedule 100 --local_epochs 1 --target_batch_size 100  ### 100 epochs
#CUDA_VISIBLE_DEVICES=1 python3 exp.py --target_learning_rate 0.05 --simplex 1 --user_number 2 --target_data_size 10000 --num_step 100  --cross_loss_diff_lambda 0 --shadow_model_number 10 --std_loss_lambda 0 --fpr_threshold 0.001 --grad_addback_weight 0 --vul_metric loss  --mixup 0 --repartition 1 --mmd_loss_lambda 0  --target_epochs 120 --dataset cifar10 --model_name alexnet --target_l2_ratio 1e-5  --schedule 100  --local_epochs 1 --target_batch_size 100  ### 100 epochs
# alexnet dpsgd done, 1e10, 1e-10
#CUDA_VISIBLE_DEVICES=2 python3 exp.py --test_result 0 --label_only_attack 1 --dpsgd 1 --grad_norm 1e10 --noise_scale 1e-10 --cross_loss_diff_lambda 0 --user_number 1  --target_data_size 20000 --num_step 200 --shadow_model_number 1  --std_loss_lambda 0 --fpr_threshold 0.001 --grad_addback_weight 0 --vul_metric loss  --mixup 0 --repartition 0 --mmd_loss_lambda 0  --target_epochs 120  --dataset cifar100 --model_name alexnet --target_learning_rate 0.01 --target_l2_ratio 1e-5  --schedule 100 --local_epochs 1 --target_batch_size 100  ### 100 epochs
# 2e-11 or 1.5e-11 not much diff. 1e10, 2e-11
#CUDA_VISIBLE_DEVICES=3 python3 exp.py --test_result 0 --label_only_attack 1 --dpsgd 1 --grad_norm 1e10 --noise_scale 2e-11 --cross_loss_diff_lambda 0 --user_number 1  --target_data_size 20000 --num_step 200 --shadow_model_number 1 --std_loss_lambda 0 --fpr_threshold 0.001 --grad_addback_weight 0 --vul_metric loss  --mixup 0 --repartition 0 --mmd_loss_lambda 0  --target_epochs 120 --dataset cifar10 --model_name alexnet --target_learning_rate 0.01 --target_l2_ratio 1e-5  --schedule 100   --local_epochs 1 --target_batch_size 100  ### 100 epochs
# alexnet hamp cifar10 done, tuning cifar100
# 0, 0.001 for cifar100, 0.001, 0.05 for cifar10, tune LR (0.1, 0.01)
# try 0.05, 0.15, 0.2
#CUDA_VISIBLE_DEVICES=0 python3 exp.py --test_result 0  --label_only_attack 1 --post_def 0  --hamp 1 --hamp_weight 0 --entropy_percentile 0.001 --cross_loss_diff_lambda 0 --user_number 1  --target_data_size 20000 --num_step 200 --shadow_model_number 1  --std_loss_lambda 0 --fpr_threshold 0.001 --grad_addback_weight 0 --vul_metric loss  --mixup 0 --repartition 0 --mmd_loss_lambda 0  --target_epochs 120  --dataset cifar100 --model_name alexnet --target_learning_rate 0.2 --target_l2_ratio 1e-5  --schedule 100 --local_epochs 1 --target_batch_size 100  ### 100 epochs
# try 0.015
#CUDA_VISIBLE_DEVICES=1 python3 exp.py --test_result 0 --label_only_attack 1 --post_def 0  --hamp 1 --hamp_weight 0.001 --entropy_percentile 0.05 --cross_loss_diff_lambda 0 --user_number 1  --target_data_size 20000 --num_step 200 --shadow_model_number 1 --std_loss_lambda 0 --fpr_threshold 0.001 --grad_addback_weight 0 --vul_metric loss  --mixup 0 --repartition 0 --mmd_loss_lambda 0  --target_epochs 120 --dataset cifar10 --model_name alexnet --target_learning_rate 0.02 --target_l2_ratio 1e-5  --schedule 100   --local_epochs 1 --target_batch_size 100  ### 100 epochs

## block for resnet
# 13
#CUDA_VISIBLE_DEVICES=0 python3 exp.py  --test_result 1 --grad_addback_weight 0 --cross_loss l1 --vul_metric loss --cross_loss_diff_lambda 13 --user_number 2 --target_data_size 10000 --num_step 100 --shadow_model_number 60 --std_loss_lambda 0 --fpr_threshold 0.001 --mixup 1 --repartition 1 --mmd_loss_lambda 0  --target_epochs 300  --dataset cifar100 --model_name resnet18 --target_learning_rate 0.1 --target_l2_ratio 1e-5  --schedule 200 250 --local_epochs 1 --target_batch_size 100  ### 100 epochs
# 3.5
#CUDA_VISIBLE_DEVICES=0 python3 exp.py   --test_result 1 --grad_addback_weight 0 --cross_loss l1  --vul_metric loss --cross_loss_diff_lambda 3.5 --user_number 2 --target_data_size 10000 --num_step 100  --shadow_model_number 60  --std_loss_lambda 0 --fpr_threshold 0.001 --mixup 1 --repartition 1 --mmd_loss_lambda 0 --target_epochs 300  --dataset cifar10 --model_name resnet18 --target_learning_rate 0.1 --target_l2_ratio 1e-5  --schedule 200 250 --local_epochs 1 --target_batch_size 100  ### 100 epochs
# resnet basecase
#CUDA_VISIBLE_DEVICES=2 python3 exp.py  --test_result 1 --cross_loss_diff_lambda 0 --user_number 1  --target_data_size 20000 --num_step 200 --shadow_model_number 60  --std_loss_lambda 0 --fpr_threshold 0.001 --grad_addback_weight 0 --vul_metric loss  --mixup 0 --repartition 1 --mmd_loss_lambda 0  --target_epochs 300  --dataset cifar100 --model_name resnet18 --target_learning_rate 0.1 --target_l2_ratio 1e-5  --schedule 200 250 --local_epochs 1 --target_batch_size 100  ### 100 epochs
#CUDA_VISIBLE_DEVICES=3 python3 exp.py  --test_result 1 --cross_loss_diff_lambda 0 --user_number 1  --target_data_size 20000 --num_step 200 --shadow_model_number 60 --std_loss_lambda 0 --fpr_threshold 0.001 --grad_addback_weight 0 --vul_metric loss  --mixup 0 --repartition 1 --mmd_loss_lambda 0  --target_epochs 300  --dataset cifar10 --model_name resnet18 --target_learning_rate 0.1 --target_l2_ratio 1e-5  --schedule 200 250 --local_epochs 1 --target_batch_size 100  ### 100 epochs
# mixup MMD
#CUDA_VISIBLE_DEVICES=2 python3 exp.py   --test_result 1 --mmd_loss_lambda 0.025 --cross_loss_diff_lambda 0 --user_number 1  --target_data_size 20000 --num_step 200 --shadow_model_number 30  --std_loss_lambda 0 --fpr_threshold 0.001 --grad_addback_weight 0 --vul_metric loss  --mixup 1 --repartition 0  --target_epochs 300  --dataset cifar100 --model_name resnet18 --target_learning_rate 0.1 --target_l2_ratio 1e-5  --schedule 200 250 --local_epochs 1 --target_batch_size 100  ### 100 epochs
#CUDA_VISIBLE_DEVICES=1 python3 exp.py  --test_result 1 --mmd_loss_lambda 0.0425 --cross_loss_diff_lambda 0 --user_number 1  --target_data_size 20000 --num_step 200 --shadow_model_number 30 --std_loss_lambda 0 --fpr_threshold 0.001 --grad_addback_weight 0 --vul_metric loss  --mixup 1 --repartition 0  --target_epochs 300  --dataset cifar10 --model_name resnet18 --target_learning_rate 0.1 --target_l2_ratio 1e-5  --schedule 200 250 --local_epochs 1 --target_batch_size 100  ### 100 epochs
# resnet num user exp
#CUDA_VISIBLE_DEVICES=0 python3 exp.py --cross_loss_diff_lambda 0 --user_number 5  --target_data_size 4000 --num_step 40 --shadow_model_number 1  --std_loss_lambda 0 --fpr_threshold 0.001 --grad_addback_weight 0 --vul_metric loss  --mixup 0 --repartition 0 --mmd_loss_lambda 0  --target_epochs 300  --dataset cifar100 --model_name resnet18 --target_learning_rate 0.1 --target_l2_ratio 1e-5  --schedule 200 250 --local_epochs 1 --target_batch_size 100  ### 100 epochs
#CUDA_VISIBLE_DEVICES=2 python3 exp.py --cross_loss_diff_lambda 0 --user_number 1  --target_data_size 20000 --num_step 200 --shadow_model_number 100 --std_loss_lambda 0 --fpr_threshold 0.001 --grad_addback_weight 0 --vul_metric loss  --mixup 0 --repartition 0 --mmd_loss_lambda 0  --target_epochs 300  --dataset cifar10 --model_name resnet18 --target_learning_rate 0.1 --target_l2_ratio 1e-5  --schedule 200 250 --local_epochs 1 --target_batch_size 100  ### 100 epochs
# resnet dpsgd done
# both 1.75e-11
#CUDA_VISIBLE_DEVICES=0 python3 exp.py  --test_result 1 --dpsgd 1 --grad_norm 1e10 --noise_scale 1.75e-11 --cross_loss_diff_lambda 0 --user_number 1  --target_data_size 20000 --num_step 200 --shadow_model_number 60  --std_loss_lambda 0 --fpr_threshold 0.001 --grad_addback_weight 0 --vul_metric loss  --mixup 0 --repartition 0 --mmd_loss_lambda 0  --target_epochs 300  --dataset cifar100 --model_name resnet18 --target_learning_rate 0.1 --target_l2_ratio 1e-5  --schedule 200 250 --local_epochs 1 --target_batch_size 100  ### 100 epochs
#CUDA_VISIBLE_DEVICES=1 python3 exp.py  --test_result 1 --dpsgd 1 --grad_norm 1e10 --noise_scale 1.75e-11 --cross_loss_diff_lambda 0 --user_number 1  --target_data_size 20000 --num_step 200 --shadow_model_number 60 --std_loss_lambda 0 --fpr_threshold 0.001 --grad_addback_weight 0 --vul_metric loss  --mixup 0 --repartition 0 --mmd_loss_lambda 0  --target_epochs 300  --dataset cifar10 --model_name resnet18 --target_learning_rate 0.1 --target_l2_ratio 1e-5  --schedule 200 250 --local_epochs 1 --target_batch_size 100  ### 100 epochs
# resnet hamp still tuning
# .cifar10 0, 0.9?
# cifar100, 0.001, 0.8
#CUDA_VISIBLE_DEVICES=2 python3 exp.py   --test_result 1 --post_def 0  --hamp 1 --hamp_weight 0.001 --entropy_percentile 0.8 --cross_loss_diff_lambda 0 --user_number 1  --target_data_size 20000 --num_step 200 --shadow_model_number 60 --std_loss_lambda 0 --fpr_threshold 0.001 --grad_addback_weight 0 --vul_metric loss  --mixup 0 --repartition 0 --mmd_loss_lambda 0  --target_epochs 300  --dataset cifar100 --model_name resnet18 --target_learning_rate 0.1 --target_l2_ratio 1e-5  --schedule 200 250 --local_epochs 1 --target_batch_size 100  ### 100 epochs
#CUDA_VISIBLE_DEVICES=3 python3 exp.py   --test_result 1 --post_def 0  --hamp 1 --hamp_weight 0 --entropy_percentile 0.9 --cross_loss_diff_lambda 0 --user_number 1  --target_data_size 20000 --num_step 200 --shadow_model_number 60 --std_loss_lambda 0 --fpr_threshold 0.001 --grad_addback_weight 0 --vul_metric loss  --mixup 0 --repartition 0 --mmd_loss_lambda 0  --target_epochs 300  --dataset cifar10 --model_name resnet18 --target_learning_rate 0.1 --target_l2_ratio 1e-5  --schedule 200 250 --local_epochs 1 --target_batch_size 100  ### 100 epochs
# to compare with selena
#CUDA_VISIBLE_DEVICES=0 python3 exp.py --grad_addback_weight 0.03 --vul_metric loss --cross_loss_diff_lambda 20 --user_number 5 --target_data_size 9900 --num_step 99 --shadow_model_number 1 --std_loss_lambda 0 --fpr_threshold 0.001 --mixup 1 --repartition 1 --mmd_loss_lambda 0  --target_epochs 300  --dataset cifar100 --model_name resnet18 --target_learning_rate 0.1 --target_l2_ratio 1e-5  --schedule 200 250 --local_epochs 1 --target_batch_size 100  ### 100 epochs

## block for densenet
#CUDA_VISIBLE_DEVICES=0 python3 exp.py   --test_result 1 --grad_addback_weight 0 --cross_loss l1  --vul_metric loss --cross_loss_diff_lambda 13 --user_number 2 --target_data_size 10000 --num_step 100 --shadow_model_number 60 --std_loss_lambda 0 --fpr_threshold 0.001 --mixup 1 --repartition 1 --mmd_loss_lambda 0 --target_epochs 400  --dataset cifar100 --model_name densenet --target_learning_rate 0.1 --target_l2_ratio 1e-5  --schedule 300 350 --local_epochs 1 --target_batch_size 100  ### 100 epochs
#CUDA_VISIBLE_DEVICES=1 python3 exp.py  --test_result 1 --grad_addback_weight 0 --cross_loss l1  --vul_metric loss --cross_loss_diff_lambda 6 --user_number 2 --target_data_size 10000 --num_step 100  --shadow_model_number 15 --std_loss_lambda 0 --fpr_threshold 0.001 --mixup 1 --repartition 1 --mmd_loss_lambda 0 --target_epochs 400  --dataset cifar10 --model_name densenet --target_learning_rate 0.1 --target_l2_ratio 1e-5  --schedule 300 350 --local_epochs 1 --target_batch_size 100  ### 100 epochs
# densenet base case
#CUDA_VISIBLE_DEVICES=1 python3 exp.py  --test_result 0 --cross_loss_diff_lambda 0 --user_number 1 --target_data_size 20000 --num_step 200 --shadow_model_number 60 --std_loss_lambda 0 --fpr_threshold 0.001 --grad_addback_weight 0 --vul_metric loss --mixup 0 --repartition 0 --mmd_loss_lambda 0 --target_epochs 400  --dataset cifar100 --model_name densenet --target_learning_rate 0.1 --target_l2_ratio 1e-5  --schedule 300 350 --local_epochs 1 --target_batch_size 100  ### 100 epochs
#CUDA_VISIBLE_DEVICES=2 python3 exp.py  --test_result 0  --cross_loss_diff_lambda 0 --user_number 1 --target_data_size 20000 --num_step 200  --shadow_model_number 60 --std_loss_lambda 0 --fpr_threshold 0.001 --grad_addback_weight 0 --vul_metric loss --mixup 0 --repartition 0 --mmd_loss_lambda 0 --target_epochs 400  --dataset cifar10 --model_name densenet --target_learning_rate 0.1 --target_l2_ratio 1e-5  --schedule 300 350 --local_epochs 1 --target_batch_size 100  ### 100 epochs
# mixup MMD
#CUDA_VISIBLE_DEVICES=2 python3 exp.py  --test_result 1  --mmd_loss_lambda 0.88 --cross_loss_diff_lambda 0 --user_number 1 --target_data_size 20000 --num_step 200 --shadow_model_number 15 --std_loss_lambda 0 --fpr_threshold 0.001 --grad_addback_weight 0 --vul_metric loss --mixup 1 --repartition 0 --target_epochs 400  --dataset cifar100 --model_name densenet --target_learning_rate 0.1 --target_l2_ratio 1e-5  --schedule 300 350 --local_epochs 1 --target_batch_size 100  ### 100 epochs
#CUDA_VISIBLE_DEVICES=3 python3 exp.py   --test_result 1  --mmd_loss_lambda 0.1375 --cross_loss_diff_lambda 0 --user_number 1 --target_data_size 20000 --num_step 200  --shadow_model_number 15 --std_loss_lambda 0 --fpr_threshold 0.001 --grad_addback_weight 0 --vul_metric loss --mixup 1 --repartition 0 --target_epochs 400  --dataset cifar10 --model_name densenet --target_learning_rate 0.1 --target_l2_ratio 1e-5  --schedule 300 350 --local_epochs 1 --target_batch_size 100  ### 100 epochs
# HAMP done
# cifar100 0.005, 0.65
# cifar10, 0.001, 0.95, try 0.1, 0.5
#rerun cifar100
#CUDA_VISIBLE_DEVICES=1 python3 exp.py   --test_result 1 --post_def 0  --hamp 1 --hamp_weight 0.005 --entropy_percentile 0.65 --mmd_loss_lambda 0 --cross_loss_diff_lambda 0 --user_number 1 --target_data_size 20000 --num_step 200 --shadow_model_number 30 --std_loss_lambda 0 --fpr_threshold 0.001 --grad_addback_weight 0 --vul_metric loss --mixup 0 --repartition 0 --target_epochs 200  --dataset cifar100 --model_name densenet --target_learning_rate 0.5 --target_l2_ratio 1e-5  --schedule 60 90 150 --local_epochs 1 --target_batch_size 100  ### 100 epochs
#CUDA_VISIBLE_DEVICES=2 python3 exp.py   --test_result 1  --post_def 0  --hamp 1 --hamp_weight 0.001 --entropy_percentile 0.95 --mmd_loss_lambda 0 --cross_loss_diff_lambda 0 --user_number 1 --target_data_size 20000 --num_step 200  --shadow_model_number 30 --std_loss_lambda 0 --fpr_threshold 0.001 --grad_addback_weight 0 --vul_metric loss --mixup 0 --repartition 0 --target_epochs 200  --dataset cifar10 --model_name densenet --target_learning_rate 0.5 --target_l2_ratio 1e-5  --schedule 60 90 150 --local_epochs 1 --target_batch_size 100  ### 100 epochs
# DPSGD done
# cifar100 5.5e-11, try 5, 6
# cifar10 2.75e-11 try 2.25, 3.25
#CUDA_VISIBLE_DEVICES=3 python3 exp.py  --test_result 0 --dpsgd 1 --grad_norm 1e10 --noise_scale 5.5e-11 --cross_loss_diff_lambda 0 --user_number 1 --target_data_size 20000 --num_step 200 --shadow_model_number 30 --std_loss_lambda 0 --fpr_threshold 0.001 --grad_addback_weight 0 --vul_metric loss --mixup 0 --repartition 0 --mmd_loss_lambda 0 --target_epochs 400  --dataset cifar100 --model_name densenet --target_learning_rate 0.1 --target_l2_ratio 1e-5  --schedule 300 350 --local_epochs 1 --target_batch_size 100  ### 100 epochs
#CUDA_VISIBLE_DEVICES=0 python3 exp.py  --test_result 1  --dpsgd 1 --grad_norm 1e10 --noise_scale 2.75e-11 --cross_loss_diff_lambda 0 --user_number 1 --target_data_size 20000 --num_step 200  --shadow_model_number 60 --std_loss_lambda 0 --fpr_threshold 0.001 --grad_addback_weight 0 --vul_metric loss --mixup 0 --repartition 0 --mmd_loss_lambda 0 --target_epochs 400  --dataset cifar10 --model_name densenet --target_learning_rate 0.1 --target_l2_ratio 1e-5  --schedule 300 350 --local_epochs 1 --target_batch_size 100  ### 100 epochs

## block for binary purchase / texas
# 30
#CUDA_VISIBLE_DEVICES=1 python3 exp.py --test_result 1 --grad_addback_weight 0 --cross_loss l1 --vul_metric loss  --cross_loss_diff_lambda 10 --user_number 4 --target_data_size 10000 --num_step 100  --shadow_model_number 50 --std_loss_lambda 0 --fpr_threshold 0.001 --mixup 0 --repartition 1 --mmd_loss_lambda 0 --target_epochs 100 --dataset texas --model_name texas --target_learning_rate 0.1 --target_l2_ratio 1e-5  --schedule 300 --local_epochs 1 --target_batch_size 100
# 40
#CUDA_VISIBLE_DEVICES=2 python3 exp.py  --test_result 1 --grad_addback_weight 0 --cross_loss l1 --vul_metric loss  --cross_loss_diff_lambda 60  --user_number 4 --target_data_size 10000 --num_step 100 --shadow_model_number 50 --std_loss_lambda 0 --fpr_threshold 0.001 --mixup 0 --repartition 1 --mmd_loss_lambda 0  --target_epochs 100 --dataset purchase --model_name purchase --target_learning_rate 0.1 --target_l2_ratio 1e-5  --schedule 150 --local_epochs 1 --target_batch_size 100
# base case
#CUDA_VISIBLE_DEVICES=2 python3 exp.py  --test_result 1  --self_swap 0 --cross_loss_diff_lambda 0  --user_number 1 --target_data_size 40000 --num_step 400  --shadow_model_number 50 --std_loss_lambda 0 --fpr_threshold 0.001 --grad_addback_weight 0 --vul_metric loss --mixup 0 --repartition 0 --mmd_loss_lambda 0 --target_epochs 100 --dataset texas --model_name texas --target_learning_rate 0.1 --target_l2_ratio 1e-5  --schedule 300 --local_epochs 1 --target_batch_size 100
#CUDA_VISIBLE_DEVICES=3 python3 exp.py  --test_result 1 --self_swap 0 --cross_loss_diff_lambda 0  --user_number 1 --target_data_size 40000 --num_step 400 --shadow_model_number 50 --std_loss_lambda 0 --fpr_threshold 0.001 --grad_addback_weight 0 --vul_metric loss --mixup 0 --repartition 0 --mmd_loss_lambda 0  --target_epochs 100 --dataset purchase --model_name purchase --target_learning_rate 0.1 --target_l2_ratio 1e-5  --schedule 150 --local_epochs 1 --target_batch_size 100
# MMD
#CUDA_VISIBLE_DEVICES=2 python3 exp.py  --test_result 1 --self_swap 0 --cross_loss_diff_lambda 0  --user_number 1 --target_data_size 40000 --num_step 400  --shadow_model_number 50 --std_loss_lambda 0 --fpr_threshold 0.001 --grad_addback_weight 0 --vul_metric loss --mixup 0 --repartition 0 --mmd_loss_lambda 500 --target_epochs 100 --dataset texas --model_name texas --target_learning_rate 0.1 --target_l2_ratio 1e-5  --schedule 300 --local_epochs 1 --target_batch_size 100
#CUDA_VISIBLE_DEVICES=1 python3 exp.py  --test_result 0 --self_swap 0 --cross_loss_diff_lambda 0  --user_number 1 --target_data_size 40000 --num_step 400 --shadow_model_number 50 --std_loss_lambda 0 --fpr_threshold 0.001 --grad_addback_weight 0 --vul_metric loss --mixup 0 --repartition 0 --mmd_loss_lambda 500 --target_epochs 100 --dataset purchase --model_name purchase --target_learning_rate 0.1 --target_l2_ratio 1e-5  --schedule 150 --local_epochs 1 --target_batch_size 100

#texas hamp, 0.1 0.001
#CUDA_VISIBLE_DEVICES=2 python3 exp.py  --test_result 1 --post_def 0 --hamp 1 --hamp_weight 0.05 --entropy_percentile 0.001 --grad_addback_weight 0 --cross_loss l1 --vul_metric loss  --cross_loss_diff_lambda 0  --user_number 1 --target_data_size 40000 --num_step 400  --shadow_model_number 50 --std_loss_lambda 0 --fpr_threshold 0.001 --mixup 0 --repartition 0 --mmd_loss_lambda 0 --target_epochs 100 --dataset texas --model_name texas --target_learning_rate 0.10 --target_l2_ratio 1e-5  --schedule 300 --local_epochs 1 --target_batch_size 100
#purchase hamp, 0.1 0.001
#CUDA_VISIBLE_DEVICES=3 python3 exp.py  --test_result 1 --post_def 0 --hamp 1 --hamp_weight 0.1 --entropy_percentile 0.001  --grad_addback_weight 0 --cross_loss l1 --vul_metric loss  --cross_loss_diff_lambda 0  --user_number 1 --target_data_size 40000 --num_step 400 --shadow_model_number 50 --std_loss_lambda 0 --fpr_threshold 0.001 --mixup 0 --repartition 0 --mmd_loss_lambda 0  --target_epochs 100 --dataset purchase --model_name purchase --target_learning_rate 0.10 --target_l2_ratio 1e-5  --schedule 100 --local_epochs 1 --target_batch_size 100

# texas dpsgd 1.05e-11
#CUDA_VISIBLE_DEVICES=0 python3 exp.py  --dpsgd 1 --grad_norm 1e10 --noise_scale 1.35e-11 --cross_loss_diff_lambda 0  --user_number 1 --target_data_size 40000 --num_step 400  --shadow_model_number 50 --std_loss_lambda 0 --fpr_threshold 0.001 --grad_addback_weight 0 --vul_metric loss --mixup 0 --repartition 0 --mmd_loss_lambda 0 --target_epochs 100 --dataset texas --model_name texas --target_learning_rate 0.1 --target_l2_ratio 1e-5  --schedule 300 --local_epochs 1 --target_batch_size 100
# purchase dpsgd, 1.5e-12
#CUDA_VISIBLE_DEVICES=0 python3 exp.py --dpsgd 1 --grad_norm 1e10 --noise_scale 8e-12 --cross_loss_diff_lambda 0  --user_number 1 --target_data_size 40000 --num_step 400 --shadow_model_number 50 --std_loss_lambda 0 --fpr_threshold 0.001 --grad_addback_weight 0 --vul_metric loss --mixup 0 --repartition 0 --mmd_loss_lambda 0  --target_epochs 100 --dataset purchase --model_name purchase --target_learning_rate 0.1 --target_l2_ratio 1e-5  --schedule 150 --local_epochs 1 --target_batch_size 100

## location 30 or 50 epoch
# 5.5
#CUDA_VISIBLE_DEVICES=0 python3 exp.py --cross_loss_diff_lambda 14 --hamp 0 --hamp_weight 0.001 --entropy_percentile 0.5  --user_number 4 --target_data_size 1000 --num_step 10 --shadow_model_number 50 --std_loss_lambda 0 --fpr_threshold 0.001 --grad_addback_weight 0 --vul_metric loss --mixup 0 --repartition 0 --mmd_loss_lambda 0  --target_epochs 100 --dataset location --model_name location --target_learning_rate 0.1 --target_l2_ratio 1e-5  --schedule 150 --local_epochs 1 --target_batch_size 100
# basecase
#CUDA_VISIBLE_DEVICES=1 python3 exp.py --cross_loss_diff_lambda 0  --hamp 0 --hamp_weight 0.001 --entropy_percentile 0  --user_number 1 --target_data_size 4000 --num_step 40 --shadow_model_number 50 --std_loss_lambda 0 --fpr_threshold 0.001 --grad_addback_weight 0 --vul_metric loss --mixup 0 --repartition 0 --mmd_loss_lambda 0  --target_epochs 100 --dataset location --model_name location --target_learning_rate 0.1 --target_l2_ratio 1e-5  --schedule 150 --local_epochs 1 --target_batch_size 100
#hamp 0.001, 0.25
#CUDA_VISIBLE_DEVICES=2 python3 exp.py --cross_loss_diff_lambda 0  --hamp 1 --hamp_weight 0.001 --entropy_percentile 0.1  --user_number 1 --target_data_size 4000 --num_step 40 --shadow_model_number 50 --std_loss_lambda 0 --fpr_threshold 0.001 --grad_addback_weight 0 --vul_metric loss --mixup 0 --repartition 0 --mmd_loss_lambda 0  --target_epochs 100 --dataset location --model_name location --target_learning_rate 0.1 --target_l2_ratio 1e-5  --schedule 150 --local_epochs 1 --target_batch_size 100
#dpsgd, 1.125e-11
#CUDA_VISIBLE_DEVICES=3 python3 exp.py --dpsgd 1 --grad_norm 1e10 --noise_scale 2e-11 --cross_loss_diff_lambda 0  --hamp 0 --hamp_weight 0.001 --entropy_percentile 0.85  --user_number 1 --target_data_size 4000 --num_step 40 --shadow_model_number 50 --std_loss_lambda 0 --fpr_threshold 0.001 --grad_addback_weight 0 --vul_metric loss --mixup 0 --repartition 0 --mmd_loss_lambda 0  --target_epochs 100 --dataset location --model_name location --target_learning_rate 0.1 --target_l2_ratio 1e-5  --schedule 150 --local_epochs 1 --target_batch_size 100
#MMD
#CUDA_VISIBLE_DEVICES=0 python3 exp.py  --mmd_loss_lambda 6.5 --cross_loss_diff_lambda 0 --user_number 1 --target_data_size 4000 --num_step 40 --shadow_model_number 50 --std_loss_lambda 0 --fpr_threshold 0.001 --grad_addback_weight 0 --vul_metric loss --mixup 0 --repartition 0 --target_epochs 100  --dataset location --model_name location --target_learning_rate 0.1 --target_l2_ratio 1e-5  --schedule 300 --local_epochs 1 --target_batch_size 100  ### 100 epochs

# 4 user, weight 6
# 2 user, weight 5
# 3 user, weight
