##### for reducing

CUDA_VISIBLE_DEVICES=1 python3 find_user_num.py --target_learning_rate 0.05 --simplex 0 --user_number 15 --target_data_size 1333  --num_step 13 --cross_loss_diff_lambda 0 --shadow_model_number 1 --std_loss_lambda 0 --fpr_threshold 0.001 --grad_addback_weight 0 --vul_metric loss  --mixup 1 --repartition 1 --mmd_loss_lambda 0  --target_epochs 800  --dataset cifar100 --model_name alexnet --target_l2_ratio 1e-5  --schedule 1000 --local_epochs 1 --target_batch_size 100  ### 100 epochs
#CUDA_VISIBLE_DEVICES=1 python3 find_user_num.py --target_learning_rate 0.05 --simplex 0 --user_number 15 --target_data_size 1333  --num_step 13 --cross_loss_diff_lambda 0 --shadow_model_number 1 --std_loss_lambda 0 --fpr_threshold 0.001 --grad_addback_weight 0 --vul_metric loss  --mixup 1 --repartition 1 --mmd_loss_lambda 0  --target_epochs 800 --dataset cifar10 --model_name alexnet --target_l2_ratio 1e-5  --schedule 1000 --local_epochs 1 --target_batch_size 100  ### 100 epochs

#CUDA_VISIBLE_DEVICES=0 python3 find_user_num.py --cross_loss_diff_lambda 0 --user_number 15 --target_data_size 1333 --num_step 13 --shadow_model_number 1  --std_loss_lambda 0 --fpr_threshold 0.001 --grad_addback_weight 0 --vul_metric loss  --mixup 1 --repartition 1 --mmd_loss_lambda 0  --target_epochs 1000  --dataset cifar100 --model_name resnet18 --target_learning_rate 0.1 --target_l2_ratio 1e-5  --schedule 1000 --local_epochs 1 --target_batch_size 100  ### 100 epochs
#CUDA_VISIBLE_DEVICES=2 python3 find_user_num.py --cross_loss_diff_lambda 0 --user_number 15  --target_data_size 1333 --num_step 13 --shadow_model_number 1  --std_loss_lambda 0 --fpr_threshold 0.001 --grad_addback_weight 0 --vul_metric loss  --mixup 1 --repartition 1 --mmd_loss_lambda 0  --target_epochs 1000  --dataset cifar10 --model_name resnet18 --target_learning_rate 0.1 --target_l2_ratio 1e-5  --schedule 1000 --local_epochs 1 --target_batch_size 100  ### 100 epochs

#CUDA_VISIBLE_DEVICES=3 python3 find_user_num.py --cross_loss_diff_lambda 0 --user_number 15  --target_data_size 1333 --num_step 13 --shadow_model_number 1  --std_loss_lambda 0 --fpr_threshold 0.001 --grad_addback_weight 0 --vul_metric loss  --mixup 1 --repartition 1 --mmd_loss_lambda 0  --target_epochs 1000  --dataset cifar100 --model_name densenet --target_learning_rate 0.1 --target_l2_ratio 1e-5  --schedule 1000 --local_epochs 1 --target_batch_size 100  ### 100 epochs
#CUDA_VISIBLE_DEVICES=0 python3 find_user_num.py --cross_loss_diff_lambda 0 --user_number 15  --target_data_size 1333 --num_step 13 --shadow_model_number 1  --std_loss_lambda 0 --fpr_threshold 0.001 --grad_addback_weight 0 --vul_metric loss  --mixup 1 --repartition 1 --mmd_loss_lambda 0  --target_epochs 1000  --dataset cifar10 --model_name densenet --target_learning_rate 0.1 --target_l2_ratio 1e-5  --schedule 1000 --local_epochs 1 --target_batch_size 100  ### 100 epochs

#CUDA_VISIBLE_DEVICES=0 python3 find_user_num.py --cross_loss_diff_lambda 0 --user_number 15  --target_data_size 2666 --num_step 26 --shadow_model_number 1  --std_loss_lambda 0 --fpr_threshold 0.001 --grad_addback_weight 0 --vul_metric loss  --mixup 0 --repartition 1 --mmd_loss_lambda 0  --target_epochs 500 --dataset purchase --model_name purchase --target_learning_rate 0.1 --target_l2_ratio 1e-5  --schedule 1000 --local_epochs 1 --target_batch_size 100  ### 100 epochs

#CUDA_VISIBLE_DEVICES=0 python3 find_user_num.py --cross_loss_diff_lambda 0 --user_number 15  --target_data_size 2666 --num_step 26 --shadow_model_number 1  --std_loss_lambda 0 --fpr_threshold 0.001 --grad_addback_weight 0 --vul_metric loss  --mixup 0 --repartition 1 --mmd_loss_lambda 0  --target_epochs 500 --dataset texas --model_name texas --target_learning_rate 0.1 --target_l2_ratio 1e-5  --schedule 1000 --local_epochs 1 --target_batch_size 100  ### 100 epochs



##### for increasing
#CUDA_VISIBLE_DEVICES=1 python3 find_user_num.py --target_learning_rate 0.02 --simplex 0 --user_number 2 --target_data_size 10000  --num_step 100 --cross_loss_diff_lambda 0 --shadow_model_number 1 --std_loss_lambda 0 --fpr_threshold 0.001 --grad_addback_weight 0 --vul_metric loss  --mixup 1 --repartition 1 --mmd_loss_lambda 0  --target_epochs 1000  --dataset cifar100 --model_name alexnet --target_l2_ratio 1e-5  --schedule 1000 --local_epochs 1 --target_batch_size 100  ### 100 epochs
#CUDA_VISIBLE_DEVICES=1 python3 find_user_num.py --target_learning_rate 0.02 --simplex 0 --user_number 2 --target_data_size 10000  --num_step 100 --cross_loss_diff_lambda 0 --shadow_model_number 1 --std_loss_lambda 0 --fpr_threshold 0.001 --grad_addback_weight 0 --vul_metric loss  --mixup 1 --repartition 1 --mmd_loss_lambda 0  --target_epochs 1000  --dataset cifar10 --model_name alexnet --target_l2_ratio 1e-5  --schedule 1000 --local_epochs 1 --target_batch_size 100  ### 100 epochs

#CUDA_VISIBLE_DEVICES=0 python3 find_user_num.py --cross_loss_diff_lambda 0 --user_number 2 --target_data_size 10000 --num_step 100 --shadow_model_number 1  --std_loss_lambda 0 --fpr_threshold 0.001 --grad_addback_weight 0 --vul_metric loss  --mixup 1 --repartition 1 --mmd_loss_lambda 0  --target_epochs 1000  --dataset cifar100 --model_name resnet18 --target_learning_rate 0.1 --target_l2_ratio 1e-5  --schedule 1000 --local_epochs 1 --target_batch_size 100  ### 100 epochs
#CUDA_VISIBLE_DEVICES=2 python3 find_user_num.py --cross_loss_diff_lambda 0 --user_number 2  --target_data_size 10000 --num_step 100 --shadow_model_number 1  --std_loss_lambda 0 --fpr_threshold 0.001 --grad_addback_weight 0 --vul_metric loss  --mixup 1 --repartition 1 --mmd_loss_lambda 0  --target_epochs 1000  --dataset cifar10 --model_name resnet18 --target_learning_rate 0.1 --target_l2_ratio 1e-5  --schedule 1000 --local_epochs 1 --target_batch_size 100  ### 100 epochs

#CUDA_VISIBLE_DEVICES=3 python3 find_user_num.py --cross_loss_diff_lambda 0 --user_number 2  --target_data_size 10000 --num_step 100 --shadow_model_number 1  --std_loss_lambda 0 --fpr_threshold 0.001 --grad_addback_weight 0 --vul_metric loss  --mixup 1 --repartition 1 --mmd_loss_lambda 0  --target_epochs 1000  --dataset cifar100 --model_name densenet --target_learning_rate 0.1 --target_l2_ratio 1e-5  --schedule 1000 --local_epochs 1 --target_batch_size 100  ### 100 epochs
#CUDA_VISIBLE_DEVICES=0 python3 find_user_num.py --cross_loss_diff_lambda 0 --user_number 2  --target_data_size 10000 --num_step 100 --shadow_model_number 1  --std_loss_lambda 0 --fpr_threshold 0.001 --grad_addback_weight 0 --vul_metric loss  --mixup 1 --repartition 1 --mmd_loss_lambda 0  --target_epochs 1000  --dataset cifar10 --model_name densenet --target_learning_rate 0.1 --target_l2_ratio 1e-5  --schedule 1000 --local_epochs 1 --target_batch_size 100  ### 100 epochs
